name: model-env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - numpy=1.21.6
  - pip=21.2.4
  - scikit-learn=0.22.1
  - pip:
    - azureml-defaults==1.47.0
    - joblib==0.14.1
    - onnxruntime==1.11.1